# Site configuration
permalink: /:title/
basecss: 
# Theme specific configuration
title: LuckyBoy
description: >
    nothing left

# Contact and social media links
exclude: ['node_modules', 'gulpfile.js', 'package.json']

kramdown:
  input: GFM

# If U enable the comment, edit disqus or duoshuo account
# before deploy your webpage
enable_comment: false

gems: ['jekyll-paginate']
# Pagination
paginate: 5
paginate_path: /archive/page:num
